// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/shhwang1227/sqlc/internal/sql/ast"
	"github.com/shhwang1227/sqlc/internal/sql/catalog"
)

func PgVisibility() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = []*catalog.Function{
		{
			Name: "pg_truncate_visibility_map",
			Args: []*catalog.Argument{
				{
					Type: &ast.TypeName{Name: "regclass"},
				},
			},
			ReturnType: &ast.TypeName{Name: "void"},
		},
	}
	return s
}
